#!/bin/bash

#######################################
#
#	run notekeep menu
#
#	author: michael kosko
#
#######################################

# put me in /usr/local/bin +x

~/notekeep/menu.sh

exit 0

