#!/bin/bash

#######################################
#
#	run notekeep menu
#
#	author: michael kosko
#
#######################################

# put me in /usr/local/bin

/usr/local/notekeep/menu.sh

exit 0

